// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: password.proto

public final class Password {
  private Password() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PasswordDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PasswordDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>string hashValue = 3;</code>
     * @return The hashValue.
     */
    java.lang.String getHashValue();
    /**
     * <code>string hashValue = 3;</code>
     * @return The bytes for hashValue.
     */
    com.google.protobuf.ByteString
        getHashValueBytes();

    /**
     * <code>string saltValue = 4;</code>
     * @return The saltValue.
     */
    java.lang.String getSaltValue();
    /**
     * <code>string saltValue = 4;</code>
     * @return The bytes for saltValue.
     */
    com.google.protobuf.ByteString
        getSaltValueBytes();
  }
  /**
   * Protobuf type {@code PasswordDetails}
   */
  public static final class PasswordDetails extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PasswordDetails)
      PasswordDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PasswordDetails.newBuilder() to construct.
    private PasswordDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PasswordDetails() {
      id_ = "";
      password_ = "";
      hashValue_ = "";
      saltValue_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PasswordDetails();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Password.internal_static_PasswordDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Password.internal_static_PasswordDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Password.PasswordDetails.class, Password.PasswordDetails.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object password_ = "";
    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    @java.lang.Override
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HASHVALUE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object hashValue_ = "";
    /**
     * <code>string hashValue = 3;</code>
     * @return The hashValue.
     */
    @java.lang.Override
    public java.lang.String getHashValue() {
      java.lang.Object ref = hashValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hashValue_ = s;
        return s;
      }
    }
    /**
     * <code>string hashValue = 3;</code>
     * @return The bytes for hashValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHashValueBytes() {
      java.lang.Object ref = hashValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hashValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SALTVALUE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object saltValue_ = "";
    /**
     * <code>string saltValue = 4;</code>
     * @return The saltValue.
     */
    @java.lang.Override
    public java.lang.String getSaltValue() {
      java.lang.Object ref = saltValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        saltValue_ = s;
        return s;
      }
    }
    /**
     * <code>string saltValue = 4;</code>
     * @return The bytes for saltValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSaltValueBytes() {
      java.lang.Object ref = saltValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        saltValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hashValue_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, hashValue_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(saltValue_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, saltValue_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hashValue_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, hashValue_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(saltValue_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, saltValue_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Password.PasswordDetails)) {
        return super.equals(obj);
      }
      Password.PasswordDetails other = (Password.PasswordDetails) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getPassword()
          .equals(other.getPassword())) return false;
      if (!getHashValue()
          .equals(other.getHashValue())) return false;
      if (!getSaltValue()
          .equals(other.getSaltValue())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (37 * hash) + HASHVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getHashValue().hashCode();
      hash = (37 * hash) + SALTVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getSaltValue().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Password.PasswordDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Password.PasswordDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Password.PasswordDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Password.PasswordDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Password.PasswordDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Password.PasswordDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Password.PasswordDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Password.PasswordDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Password.PasswordDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Password.PasswordDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Password.PasswordDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Password.PasswordDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Password.PasswordDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PasswordDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PasswordDetails)
        Password.PasswordDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Password.internal_static_PasswordDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Password.internal_static_PasswordDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Password.PasswordDetails.class, Password.PasswordDetails.Builder.class);
      }

      // Construct using Password.PasswordDetails.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        password_ = "";
        hashValue_ = "";
        saltValue_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Password.internal_static_PasswordDetails_descriptor;
      }

      @java.lang.Override
      public Password.PasswordDetails getDefaultInstanceForType() {
        return Password.PasswordDetails.getDefaultInstance();
      }

      @java.lang.Override
      public Password.PasswordDetails build() {
        Password.PasswordDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Password.PasswordDetails buildPartial() {
        Password.PasswordDetails result = new Password.PasswordDetails(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Password.PasswordDetails result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.password_ = password_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.hashValue_ = hashValue_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.saltValue_ = saltValue_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Password.PasswordDetails) {
          return mergeFrom((Password.PasswordDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Password.PasswordDetails other) {
        if (other == Password.PasswordDetails.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getHashValue().isEmpty()) {
          hashValue_ = other.hashValue_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getSaltValue().isEmpty()) {
          saltValue_ = other.saltValue_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                password_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                hashValue_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                saltValue_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 2;</code>
       * @return The password.
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       * @return The bytes for password.
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        password_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        password_ = getDefaultInstance().getPassword();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        password_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object hashValue_ = "";
      /**
       * <code>string hashValue = 3;</code>
       * @return The hashValue.
       */
      public java.lang.String getHashValue() {
        java.lang.Object ref = hashValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          hashValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string hashValue = 3;</code>
       * @return The bytes for hashValue.
       */
      public com.google.protobuf.ByteString
          getHashValueBytes() {
        java.lang.Object ref = hashValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hashValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hashValue = 3;</code>
       * @param value The hashValue to set.
       * @return This builder for chaining.
       */
      public Builder setHashValue(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        hashValue_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string hashValue = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHashValue() {
        hashValue_ = getDefaultInstance().getHashValue();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string hashValue = 3;</code>
       * @param value The bytes for hashValue to set.
       * @return This builder for chaining.
       */
      public Builder setHashValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        hashValue_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object saltValue_ = "";
      /**
       * <code>string saltValue = 4;</code>
       * @return The saltValue.
       */
      public java.lang.String getSaltValue() {
        java.lang.Object ref = saltValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          saltValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string saltValue = 4;</code>
       * @return The bytes for saltValue.
       */
      public com.google.protobuf.ByteString
          getSaltValueBytes() {
        java.lang.Object ref = saltValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          saltValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string saltValue = 4;</code>
       * @param value The saltValue to set.
       * @return This builder for chaining.
       */
      public Builder setSaltValue(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        saltValue_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string saltValue = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSaltValue() {
        saltValue_ = getDefaultInstance().getSaltValue();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string saltValue = 4;</code>
       * @param value The bytes for saltValue to set.
       * @return This builder for chaining.
       */
      public Builder setSaltValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        saltValue_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PasswordDetails)
    }

    // @@protoc_insertion_point(class_scope:PasswordDetails)
    private static final Password.PasswordDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Password.PasswordDetails();
    }

    public static Password.PasswordDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PasswordDetails>
        PARSER = new com.google.protobuf.AbstractParser<PasswordDetails>() {
      @java.lang.Override
      public PasswordDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PasswordDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PasswordDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Password.PasswordDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EmptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Empty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code Empty}
   */
  public static final class Empty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Empty)
      EmptyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Empty.newBuilder() to construct.
    private Empty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Empty() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Empty();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Password.internal_static_Empty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Password.internal_static_Empty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Password.Empty.class, Password.Empty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Password.Empty)) {
        return super.equals(obj);
      }
      Password.Empty other = (Password.Empty) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Password.Empty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Password.Empty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Password.Empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Password.Empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Password.Empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Password.Empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Password.Empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Password.Empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Password.Empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Password.Empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Password.Empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Password.Empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Password.Empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Empty)
        Password.EmptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Password.internal_static_Empty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Password.internal_static_Empty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Password.Empty.class, Password.Empty.Builder.class);
      }

      // Construct using Password.Empty.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Password.internal_static_Empty_descriptor;
      }

      @java.lang.Override
      public Password.Empty getDefaultInstanceForType() {
        return Password.Empty.getDefaultInstance();
      }

      @java.lang.Override
      public Password.Empty build() {
        Password.Empty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Password.Empty buildPartial() {
        Password.Empty result = new Password.Empty(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Password.Empty) {
          return mergeFrom((Password.Empty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Password.Empty other) {
        if (other == Password.Empty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Empty)
    }

    // @@protoc_insertion_point(class_scope:Empty)
    private static final Password.Empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Password.Empty();
    }

    public static Password.Empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Empty>
        PARSER = new com.google.protobuf.AbstractParser<Empty>() {
      @java.lang.Override
      public Empty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Empty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Empty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Password.Empty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PasswordListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PasswordList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .PasswordDetails passwords = 1;</code>
     */
    java.util.List<Password.PasswordDetails> 
        getPasswordsList();
    /**
     * <code>repeated .PasswordDetails passwords = 1;</code>
     */
    Password.PasswordDetails getPasswords(int index);
    /**
     * <code>repeated .PasswordDetails passwords = 1;</code>
     */
    int getPasswordsCount();
    /**
     * <code>repeated .PasswordDetails passwords = 1;</code>
     */
    java.util.List<? extends Password.PasswordDetailsOrBuilder> 
        getPasswordsOrBuilderList();
    /**
     * <code>repeated .PasswordDetails passwords = 1;</code>
     */
    Password.PasswordDetailsOrBuilder getPasswordsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code PasswordList}
   */
  public static final class PasswordList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PasswordList)
      PasswordListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PasswordList.newBuilder() to construct.
    private PasswordList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PasswordList() {
      passwords_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PasswordList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Password.internal_static_PasswordList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Password.internal_static_PasswordList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Password.PasswordList.class, Password.PasswordList.Builder.class);
    }

    public static final int PASSWORDS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<Password.PasswordDetails> passwords_;
    /**
     * <code>repeated .PasswordDetails passwords = 1;</code>
     */
    @java.lang.Override
    public java.util.List<Password.PasswordDetails> getPasswordsList() {
      return passwords_;
    }
    /**
     * <code>repeated .PasswordDetails passwords = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends Password.PasswordDetailsOrBuilder> 
        getPasswordsOrBuilderList() {
      return passwords_;
    }
    /**
     * <code>repeated .PasswordDetails passwords = 1;</code>
     */
    @java.lang.Override
    public int getPasswordsCount() {
      return passwords_.size();
    }
    /**
     * <code>repeated .PasswordDetails passwords = 1;</code>
     */
    @java.lang.Override
    public Password.PasswordDetails getPasswords(int index) {
      return passwords_.get(index);
    }
    /**
     * <code>repeated .PasswordDetails passwords = 1;</code>
     */
    @java.lang.Override
    public Password.PasswordDetailsOrBuilder getPasswordsOrBuilder(
        int index) {
      return passwords_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < passwords_.size(); i++) {
        output.writeMessage(1, passwords_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < passwords_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, passwords_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Password.PasswordList)) {
        return super.equals(obj);
      }
      Password.PasswordList other = (Password.PasswordList) obj;

      if (!getPasswordsList()
          .equals(other.getPasswordsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPasswordsCount() > 0) {
        hash = (37 * hash) + PASSWORDS_FIELD_NUMBER;
        hash = (53 * hash) + getPasswordsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Password.PasswordList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Password.PasswordList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Password.PasswordList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Password.PasswordList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Password.PasswordList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Password.PasswordList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Password.PasswordList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Password.PasswordList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Password.PasswordList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Password.PasswordList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Password.PasswordList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Password.PasswordList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Password.PasswordList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PasswordList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PasswordList)
        Password.PasswordListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Password.internal_static_PasswordList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Password.internal_static_PasswordList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Password.PasswordList.class, Password.PasswordList.Builder.class);
      }

      // Construct using Password.PasswordList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (passwordsBuilder_ == null) {
          passwords_ = java.util.Collections.emptyList();
        } else {
          passwords_ = null;
          passwordsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Password.internal_static_PasswordList_descriptor;
      }

      @java.lang.Override
      public Password.PasswordList getDefaultInstanceForType() {
        return Password.PasswordList.getDefaultInstance();
      }

      @java.lang.Override
      public Password.PasswordList build() {
        Password.PasswordList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Password.PasswordList buildPartial() {
        Password.PasswordList result = new Password.PasswordList(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(Password.PasswordList result) {
        if (passwordsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            passwords_ = java.util.Collections.unmodifiableList(passwords_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.passwords_ = passwords_;
        } else {
          result.passwords_ = passwordsBuilder_.build();
        }
      }

      private void buildPartial0(Password.PasswordList result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Password.PasswordList) {
          return mergeFrom((Password.PasswordList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Password.PasswordList other) {
        if (other == Password.PasswordList.getDefaultInstance()) return this;
        if (passwordsBuilder_ == null) {
          if (!other.passwords_.isEmpty()) {
            if (passwords_.isEmpty()) {
              passwords_ = other.passwords_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePasswordsIsMutable();
              passwords_.addAll(other.passwords_);
            }
            onChanged();
          }
        } else {
          if (!other.passwords_.isEmpty()) {
            if (passwordsBuilder_.isEmpty()) {
              passwordsBuilder_.dispose();
              passwordsBuilder_ = null;
              passwords_ = other.passwords_;
              bitField0_ = (bitField0_ & ~0x00000001);
              passwordsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPasswordsFieldBuilder() : null;
            } else {
              passwordsBuilder_.addAllMessages(other.passwords_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                Password.PasswordDetails m =
                    input.readMessage(
                        Password.PasswordDetails.parser(),
                        extensionRegistry);
                if (passwordsBuilder_ == null) {
                  ensurePasswordsIsMutable();
                  passwords_.add(m);
                } else {
                  passwordsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<Password.PasswordDetails> passwords_ =
        java.util.Collections.emptyList();
      private void ensurePasswordsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          passwords_ = new java.util.ArrayList<Password.PasswordDetails>(passwords_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Password.PasswordDetails, Password.PasswordDetails.Builder, Password.PasswordDetailsOrBuilder> passwordsBuilder_;

      /**
       * <code>repeated .PasswordDetails passwords = 1;</code>
       */
      public java.util.List<Password.PasswordDetails> getPasswordsList() {
        if (passwordsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(passwords_);
        } else {
          return passwordsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .PasswordDetails passwords = 1;</code>
       */
      public int getPasswordsCount() {
        if (passwordsBuilder_ == null) {
          return passwords_.size();
        } else {
          return passwordsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .PasswordDetails passwords = 1;</code>
       */
      public Password.PasswordDetails getPasswords(int index) {
        if (passwordsBuilder_ == null) {
          return passwords_.get(index);
        } else {
          return passwordsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .PasswordDetails passwords = 1;</code>
       */
      public Builder setPasswords(
          int index, Password.PasswordDetails value) {
        if (passwordsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePasswordsIsMutable();
          passwords_.set(index, value);
          onChanged();
        } else {
          passwordsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PasswordDetails passwords = 1;</code>
       */
      public Builder setPasswords(
          int index, Password.PasswordDetails.Builder builderForValue) {
        if (passwordsBuilder_ == null) {
          ensurePasswordsIsMutable();
          passwords_.set(index, builderForValue.build());
          onChanged();
        } else {
          passwordsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PasswordDetails passwords = 1;</code>
       */
      public Builder addPasswords(Password.PasswordDetails value) {
        if (passwordsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePasswordsIsMutable();
          passwords_.add(value);
          onChanged();
        } else {
          passwordsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .PasswordDetails passwords = 1;</code>
       */
      public Builder addPasswords(
          int index, Password.PasswordDetails value) {
        if (passwordsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePasswordsIsMutable();
          passwords_.add(index, value);
          onChanged();
        } else {
          passwordsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PasswordDetails passwords = 1;</code>
       */
      public Builder addPasswords(
          Password.PasswordDetails.Builder builderForValue) {
        if (passwordsBuilder_ == null) {
          ensurePasswordsIsMutable();
          passwords_.add(builderForValue.build());
          onChanged();
        } else {
          passwordsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PasswordDetails passwords = 1;</code>
       */
      public Builder addPasswords(
          int index, Password.PasswordDetails.Builder builderForValue) {
        if (passwordsBuilder_ == null) {
          ensurePasswordsIsMutable();
          passwords_.add(index, builderForValue.build());
          onChanged();
        } else {
          passwordsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PasswordDetails passwords = 1;</code>
       */
      public Builder addAllPasswords(
          java.lang.Iterable<? extends Password.PasswordDetails> values) {
        if (passwordsBuilder_ == null) {
          ensurePasswordsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, passwords_);
          onChanged();
        } else {
          passwordsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .PasswordDetails passwords = 1;</code>
       */
      public Builder clearPasswords() {
        if (passwordsBuilder_ == null) {
          passwords_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          passwordsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .PasswordDetails passwords = 1;</code>
       */
      public Builder removePasswords(int index) {
        if (passwordsBuilder_ == null) {
          ensurePasswordsIsMutable();
          passwords_.remove(index);
          onChanged();
        } else {
          passwordsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .PasswordDetails passwords = 1;</code>
       */
      public Password.PasswordDetails.Builder getPasswordsBuilder(
          int index) {
        return getPasswordsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .PasswordDetails passwords = 1;</code>
       */
      public Password.PasswordDetailsOrBuilder getPasswordsOrBuilder(
          int index) {
        if (passwordsBuilder_ == null) {
          return passwords_.get(index);  } else {
          return passwordsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .PasswordDetails passwords = 1;</code>
       */
      public java.util.List<? extends Password.PasswordDetailsOrBuilder> 
           getPasswordsOrBuilderList() {
        if (passwordsBuilder_ != null) {
          return passwordsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(passwords_);
        }
      }
      /**
       * <code>repeated .PasswordDetails passwords = 1;</code>
       */
      public Password.PasswordDetails.Builder addPasswordsBuilder() {
        return getPasswordsFieldBuilder().addBuilder(
            Password.PasswordDetails.getDefaultInstance());
      }
      /**
       * <code>repeated .PasswordDetails passwords = 1;</code>
       */
      public Password.PasswordDetails.Builder addPasswordsBuilder(
          int index) {
        return getPasswordsFieldBuilder().addBuilder(
            index, Password.PasswordDetails.getDefaultInstance());
      }
      /**
       * <code>repeated .PasswordDetails passwords = 1;</code>
       */
      public java.util.List<Password.PasswordDetails.Builder> 
           getPasswordsBuilderList() {
        return getPasswordsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Password.PasswordDetails, Password.PasswordDetails.Builder, Password.PasswordDetailsOrBuilder> 
          getPasswordsFieldBuilder() {
        if (passwordsBuilder_ == null) {
          passwordsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Password.PasswordDetails, Password.PasswordDetails.Builder, Password.PasswordDetailsOrBuilder>(
                  passwords_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          passwords_ = null;
        }
        return passwordsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PasswordList)
    }

    // @@protoc_insertion_point(class_scope:PasswordList)
    private static final Password.PasswordList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Password.PasswordList();
    }

    public static Password.PasswordList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PasswordList>
        PARSER = new com.google.protobuf.AbstractParser<PasswordList>() {
      @java.lang.Override
      public PasswordList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PasswordList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PasswordList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Password.PasswordList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PasswordDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PasswordDetails_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PasswordList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PasswordList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016password.proto\"U\n\017PasswordDetails\022\n\n\002i" +
      "d\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\022\021\n\thashValue\030\003" +
      " \001(\t\022\021\n\tsaltValue\030\004 \001(\t\"\007\n\005Empty\"3\n\014Pass" +
      "wordList\022#\n\tpasswords\030\001 \003(\0132\020.PasswordDe" +
      "tails2\265\001\n\017PasswordService\022,\n\021RetrievePas" +
      "swords\022\006.Empty\032\r.PasswordList\"\000\0225\n\rAddNe" +
      "wDetails\022\020.PasswordDetails\032\020.PasswordDet" +
      "ails\"\000\022=\n\025UpdatePasswordDetails\022\020.Passwo" +
      "rdDetails\032\020.PasswordDetails\"\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PasswordDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PasswordDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PasswordDetails_descriptor,
        new java.lang.String[] { "Id", "Password", "HashValue", "SaltValue", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_PasswordList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PasswordList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PasswordList_descriptor,
        new java.lang.String[] { "Passwords", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
